name: recommendations
channels:
- anaconda
- conda-forge
- defaults
dependencies:
    - python
    - numpy
    - matplotlib
    - pandas
    - scikit-learn
    - plotly
    - hurry.filesize
    - pydot
    - jupyterlab
    - findspark
    - pyyaml
    - humanize
    - pip
    - pip:
        - tensorflow
        # - tensorflow-recommenders
        - tensorflow-datasets
        - ipywidgets
        - ray
        - modin[ray]
        - keras-tuner
        - pyspark>3.0.0

