name: recommendations
channels:
- anaconda
- conda-forge
- defaults
dependencies:
    - python>=3.7
    - numpy
    - matplotlib
    - pandas
    - jupyterlab
    - scikit-learn
    - plotly
    - hurry.filesize
    - pydot
    - jupyterlab
    - pip
    - pip:
        - tensorflow
