name: recommendations
channels:
- anaconda
- conda-forge
- conda-forge/label/cf201901
- conda-forge/label/cf202003
- defaults
dependencies:
    - python
    - numpy
    - matplotlib
    - pandas
    - jupyterlab
    - scikit-learn
    - plotly
    - hurry.filesize
    - pydot
    - jupyterlab
    - pyspark>=3.0.0
    - findspark
    - pyyaml
    - pip
    - pip:
        #- tensorflow>=2.3.0
        - tf-nightly-gpu