name: recommendations
channels:
- anaconda
- conda-forge
- defaults
dependencies:
    - python=3.6
    - numpy
    - matplotlib
    - pandas
    - jupyterlab
    - scikit-learn
    - plotly
    - hurry.filesize
    - pydot
    - jupyterlab
    - pyspark>=3.0.0
    - findspark
    - pyyaml
    - humanize
    - pip
    - pip:
        - tensorflow
        - ray
        - modin[ray]
        - keras-tuner
